export enum ConnectionStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED'
}

export enum NotificationType {
  CONNECTION_REQUEST = 'CONNECTION_REQUEST',
  CONNECTION_ACCEPTED = 'CONNECTION_ACCEPTED',
  SKILL_ENDORSEMENT = 'SKILL_ENDORSEMENT',
  NEW_BLOG_POST = 'NEW_BLOG_POST'
}

export enum SkillCategory {
  FRONTEND = 'FRONTEND',
  BACKEND = 'BACKEND',
  DATABASE = 'DATABASE',
  DEVOPS = 'DEVOPS',
  MOBILE = 'MOBILE',
  AI_ML = 'AI_ML',
  TOOLS = 'TOOLS',
  OTHER = 'OTHER'
}
